### PR TITLE
Correct local development docs

### PR DESCRIPTION
**Pull request by MgenGlder**
## Summary
@jimwallace335 discovered that our local development docs were out of date when he tried to run everything on his machine. This PR updates them and adds the correct URI's to the `settings.py` file so local development is successful.

### CODE REVIEW

**Review by dXu23 — COMMENTED** [review]
Looks good to me. I think that in the future, if the web app grows complex enough, we potentially might want separate settings for dev and production.

**Comment by MgenGlder** [comment]
> Looks good to me. I think that in the future, if the web app grows complex enough, we potentially might want separate settings for dev and production.

Sounds good. I'll look to draft a PR for the above. @dXu23 do you mind giving this PR a 👍🏾 so I can merge it? I think the previous comment didn't actually approve.

**Comment by MgenGlder** [comment]
PR for separating `settings.py` by environment can be found [here](https://github.com/dearborn-coding-club/website-base-backend/issues/29).

**Review by dXu23 — APPROVED** [review]
LGTM

**Pull request merged**
